######################################
###       CreeperHeal v 5.0        ###
######################################
###         by nitnelave           ###
######################################
#Default config
#
#Feel free to test the settings for "replacement" and the worlds
#but I advise against changing the "advanced" section if you don't know exactly what you're doing
#
#
#
#
#This first section is about how the blocks are goind to get replaced
#
#
#   How many seconds before the explosion/burnt block starts healing
wait-before-heal:
  explosions: 60
  fire: 45
#   if block-per-block is disabled, all the blocks of an explosion will be replaced at the same time
block-per-block:
  enabled: true
  interval: 20
#  If true, the bricks destroyed by an explosion will come back as cracked
crack-destroyed-bricks: false
#  chests and containers protection
ignore-chests:
# Protects all of the chests, whether they are protected or not, when set to true
  all: false
# Protects only protected chests (by Lockette or LWC) when set to true
  protected: false

